apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "blue-pool"
  namespace: kube-system
spec:
  blocks:
    - start: "192.168.4.2"
      stop: "192.168.4.250"
  serviceSelector:
    matchLabels:
      color: blue
