global:
  hosts:
    domain: gitlab.elastichomelab.com
    externalIP: 192.168.5.4

certmanager-issuer:
  email: dbstjdghks25@gmail.com

# 글로벌 보안 컨텍스트 설정
global:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

# PostgreSQL 보안 설정
postgresql:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
    runAsNonRoot: true
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

# Redis 보안 설정
redis:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
    runAsNonRoot: true
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

gitlab:
  gitaly:
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
      runAsNonRoot: true
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
